name: hi3d
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.30.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - av==12.1.0
      - basicsr==1.4.2
      - beartype==0.18.5
      - black==23.7.0
      - blinker==1.8.2
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - carvekit-colab==4.1.2
      - certifi==2022.12.7
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - clip==1.0
      - cmake==3.29.3
      - co3d==2.1.0
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cupy==13.1.0
      - cycler==0.12.1
      - datasets==2.20.0
      - decorator==4.4.2
      - deepspeed==0.14.2
      - diffusers==0.28.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.112.0
      - fastrlock==0.8.2
      - filelock==3.13.1
      - fire==0.6.0
      - flatbuffers==24.3.25
      - fonttools==4.52.4
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - h11==0.14.0
      - h5py==3.11.0
      - hjson==3.1.0
      - huggingface-hub==0.23.2
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.34.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==7.1.0
      - invisible-watermark==0.2.0
      - iopath==0.1.10
      - ipython==8.25.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - keras==3.3.3
      - kiui==0.2.9
      - kiwisolver==1.4.5
      - kornia==0.6.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.2
      - lit==18.1.6
      - llvmlite==0.42.0
      - lmdb==1.4.1
      - loguru==0.7.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapy==1.2.2
      - ml-dtypes==0.3.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - natsort==8.4.0
      - netron==7.8.4
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.59.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nvitop==1.3.2
      - objprint==0.2.3
      - omegaconf==2.3.0
      - onnxruntime==1.18.0
      - open-clip-torch==2.24.0
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.10.0.82
      - opt-einsum==3.3.0
      - optree==0.11.0
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.2
      - plyfile==1.0.3
      - pooch==1.8.2
      - portalocker==2.10.0
      - proglog==0.1.10
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pudb==2024.1
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pydantic==2.7.3
      - pydantic-core==2.18.4
      - pydeck==0.9.1
      - pydeprecate==0.3.1
      - pygments==2.18.0
      - pymatting==1.1.12
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytorch-lightning==1.5.0
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.5.15
      - rembg==2.0.57
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-image==0.23.2
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - sgm==0.1.0
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.37.2
      - streamlit==1.35.0
      - streamlit-keyup==0.2.0
      - sympy==1.12
      - tabulate==0.9.0
      - taming-transformers==0.0.1
      - tb-nightly==2.18.0a20240613
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - test-tube==0.7.5
      - tifffile==2024.5.22
      - timm==0.6.12
      - tinycudann==1.7
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.0.1
      - torch-efficient-distloss==0.1.3
      - torchaudio==2.0.2
      - torchdata==0.6.1
      - torchmetrics==1.4.0.post0
      - torchvision==0.15.2
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.43.3
      - triton==2.0.0
      - typing-extensions==4.9.0
      - tyro==0.8.4
      - tzdata==2024.1
      - urllib3==1.26.13
      - urwid==2.6.12
      - urwid-readline==0.14
      - uvicorn==0.30.4
      - varname==0.13.1
      - wandb==0.17.0
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xformers==0.0.22
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.19.0
prefix: /mnt/afs_intern/yhb/anaconda3/envs/general
